[package]
name = "hex-utils"
version = "0.1.0"
edition = "2021"
description = "Utilities for working with hexadecimal numbers"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
